<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="40" started-at="2013-11-26T22:57:27Z" finished-at="2013-11-26T22:57:27Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="40" started-at="2013-11-26T22:57:27Z" finished-at="2013-11-26T22:57:27Z">
      <class name="test.SortedKeyValueTest">
        <test-method status="PASS" signature="testZAdd()[pri:0, instance:test.SortedKeyValueTest@2c011b16]" name="testZAdd" duration-ms="17" started-at="2013-11-27T04:27:27Z" finished-at="2013-11-27T04:27:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testZAdd -->
        <test-method status="PASS" signature="testZCount()[pri:0, instance:test.SortedKeyValueTest@2c011b16]" name="testZCount" duration-ms="2" started-at="2013-11-27T04:27:27Z" finished-at="2013-11-27T04:27:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testZCount -->
        <test-method status="FAIL" signature="testZRange()[pri:0, instance:test.SortedKeyValueTest@2c011b16]" name="testZRange" duration-ms="2" started-at="2013-11-27T04:27:27Z" finished-at="2013-11-27T04:27:27Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [6] but found [4]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [6] but found [4]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:370)
	at org.testng.Assert.assertEquals(Assert.java:380)
	at test.SortedKeyValueTest.testZRange(SortedKeyValueTest.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testZRange -->
      </class> <!-- test.SortedKeyValueTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
